### PR TITLE
Dividend Queries

### PR DESCRIPTION
**Pull request by dissolved**
Hi,

I made the following changes to support querying for dividends paid. Useful if you want to calculate the dividend adjusted rate of return on an investment.

Thanks,
Ryan Sandridge

### CODE REVIEW

**Comment by nas** [comment]
Thanks Ryan, 

And apologies for late repIy because I am currently on holiday for a couple of weeks will have a look at this when I am back.

Many thanks.

nas

**Comment by dissolved** [comment]
Enjoy your holiday!

**Comment by nas** [comment]
Hi Ryan,

I have merged your changes and pushed it to the gemcutter. I did revert your one commit '2fecdd0' as I did upgrade and tested the specs with 2.1.0.

I have also added your name to the README.

Now you can run the rspec tests with "rspec spec" and cucumber with "rake cucumber".

I may need to do some refactoring as you added the dividend for which the interval temp does not feel appropriate. I will do it as soon as I get the time.

Any way thanks for the contribution.

Please let me know if you have any clarification

Cheers

nas

**Comment by dissolved** [comment]
Cool, thanks for the attribution.
Cheers,
Ryan

**Pull request closed without merging**
